# SPRING PROFILES
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql:3306/my_daily_cost?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: 123456

  redis:
    database: 0
    host: redis
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000

# server properties
rsa:
  key:
    path: /data/deploy/server/license/

pwd:
  salt:

jwt:
  secret:
    key:

logback:
  path: /home/tonyjiang/log/