# Server settings
server:
    port: 1310
    address: localhost
    tomcat:
        uri-encoding: utf-8
# SPRING PROFILES
spring:
#    spring.jackson.default-property-inclusion=NON_NULL
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.force: true
        encoding.enabled: true

        multipart:
          max-file-size: 30Mb
          max-request-size: 40Mb
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my_2017_cost?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: fixture

    redis:
      database: 0
      host: 112.74.175.214
      port: 6379
      password: 
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 3000

    thymeleaf:
      cache: false
# MyBatis
mybatis:
    typeAliasesPackage: com.tony.billing.entity
    mapperLocations: classpath:/sqlMapper/*SqlMap.xml
    configLocation: classpath:/mybatis-config.xml

# server properties
rsa:
    key:
        path: D:/
