# Server settings
server:
    port: 1310
    address: 0.0.0.0
    tomcat:
        uri-encoding: utf-8
# SPRING PROFILES
spring:
#    spring.jackson.default-property-inclusion=NON_NULL
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.force: true
        encoding.enabled: true

        multipart:
          max-file-size: 30Mb
          max-request-size: 40Mb

    profiles:
      active: @activatedProperties@
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
# MyBatis
mybatis:
    typeAliasesPackage: com.tony.billing.entity
    mapperLocations: classpath:/sqlMapper/*SqlMap.xml
    configLocation: classpath:/mybatis-config.xml
